name: Pull Request Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - CMakeFiles.txt
      - src/**
      - tests/**

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]

    uses: ./.github/workflows/build.yml
