name: Build and Upload

on:
  pull_request:
    paths:
      - CMakeFiles.txt
      - src/**
      - tests/**

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]

    uses: ./github/workflows/build.yml